import Ok from './Ok'
import Cancel from './Cancel'
import Save from './Save'
import Redo from './Redo'
import Undo from './Undo'
import Mosaic from './Mosaic'
import Text from './Text'
import Brush from './Brush'
import Arrow from './Arrow'
import Ellipse from './Ellipse'
import Rectangle from './Rectangle'
import Translate from './Translate'
import OCR from './OCR'

export default [Rectangle, Ellipse, Arrow, Brush, Text, Mosaic, '|', Translate, OCR, '|', Undo, Redo, '|', Save, Cancel, Ok]
